### ISSUE TITLE
Make avatar settings filterable

### ISSUE THREAD

**Issue by actual-saurabh** [yapapaya/live-comment-preview#10]
In https://github.com/yapapaya/live-comment-preview/blob/master/live-comment-preview.php#L100-L102, the avatar settings are fixed. Apart from picking up these values from WP defaults in #9, these should be filterable by a theme, plugin developer

**Comment by mariadanieldeepak** [comment]
The Avatar Settings are obtained from WordPress database (https://github.com/yapapaya/live-comment-preview/blob/master/class-live-comment-preview.php#L379). These settings can be changed from the WordPress dashboard.

There is no size settings for Avatar in the dashboard and this depends on the Theme. Even the size of the Avatar is obtained from the Theme (https://github.com/yapapaya/live-comment-preview/blob/master/class-live-comment-preview.php#L303).

Kindly do let me know if it is still required to make this property filterable.

**Comment by actual-saurabh** [comment]
Then, no, since anyone wanting to filter the avatar settings could just filter the WordPress ones.

**Comment by mariadanieldeepak** [comment]
@actual-saurabh Alright, thanks.
