### ISSUE TITLE
Rename include to templates

### ISSUE THREAD

**Issue by actual-saurabh** [yapapaya/live-comment-preview#15]
The term includes is used for php includes or even classes that need to be included.

Semi php, but mostly html, WordPress theme template like files are usually placed in templates.

**Comment by chainedcoder** [comment]
I'll do this Rename include to templates #15

**Comment by mariadanieldeepak** [comment]
Hello @stevenkayter, I have completed and tested this as part of #17. Kindly do take up other issues else.
