### ISSUE TITLE
Move all non-PHP code to separate file

### ISSUE THREAD

**Issue by actual-saurabh** [yapapaya/live-comment-preview#3]
The current code contains a mix of PHP and jQuery within the same file

**Comment by actual-saurabh** [comment]
https://github.com/yapapaya/live-comment-preview/blob/master/live-comment-preview.php#L347-L367 contains html that should go in a separate file that can then be included and assigned to a variable.

**Comment by JamesFranc** [comment]
@actual-saurabh The last pull request included the change to the $template variable I used file_get_contents instead of include, and am not sure if it will work as expected. Might want to give that a look.

**Comment by actual-saurabh** [comment]
@JamesFranc sure, thanks for the heads up!
